(* generated by scripts/assets/texture_tints.py from opensoldat-base's
 * shared/textures (CC BY 4.0): each texture's mean colour, by its file's
 * name without the extension, in small letters *)
let all : (string * (int * int * int)) list =
  [
    ("ananas", (187, 187, 187));
    ("ancientwall", (142, 127, 127));
    ("awokado", (130, 113, 72));
    ("banana", (110, 114, 111));
    ("ctf_cobra2", (112, 120, 103));
    ("ctf_steel", (141, 141, 141));
    ("cytryna", (172, 172, 172));
    ("dankoe", (161, 161, 161));
    ("default", (187, 187, 187));
    ("dorothy", (84, 98, 90));
    ("drymud", (139, 118, 76));
    ("drysand", (108, 94, 66));
    ("earthen", (198, 181, 154));
    ("grejfrut", (111, 95, 80));
    ("gruszka", (186, 186, 186));
    ("jablko", (86, 112, 21));
    ("kamibeach", (137, 123, 74));
    ("kiwi", (70, 71, 68));
    ("kokos", (187, 170, 141));
    ("malaga", (52, 46, 35));
    ("malina", (155, 156, 156));
    ("mandarynka", (156, 156, 156));
    ("melon", (151, 151, 151));
    ("metroid", (111, 111, 111));
    ("mossgreen", (121, 130, 59));
    ("mtex_desert", (175, 169, 160));
    ("mtk_death", (78, 78, 78));
    ("pomarancz", (114, 121, 106));
    ("porzeczka", (75, 78, 75));
    ("potato", (154, 132, 83));
    ("potato2", (155, 133, 87));
    ("poziomka", (154, 154, 155));
    ("riverbed", (136, 118, 73));
    ("rodzynka", (103, 94, 39));
    ("rustedmetal", (173, 120, 92));
    ("sk_aztec", (132, 122, 95));
    ("snakedesert", (173, 156, 125));
    ("snowice", (203, 205, 210));
    ("stone03", (167, 133, 104));
    ("truskawka", (81, 93, 75));
    ("ut_ground3", (99, 90, 80));
    ("vtt34", (146, 146, 146));
    ("vtt_wct (34)", (127, 134, 146));
    ("wisnia", (81, 67, 46));
    ("wisnia2", (148, 139, 126));
    ("xt_ap_grasrock_02", (143, 139, 121));
    ("xt_autumgrassrock", (125, 116, 104));
    ("xt_forrestdirtrock", (105, 99, 81));
    ("zak_grassstone6", (82, 83, 40));
  ]
