(* Claude Code
 *
 * Copyright (C) 2026 Yoann Padioleau
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public License
 * (LGPL) as published by the Free Software Foundation; either version
 * 2 of the License, or (at your option) any later version.
 *)
(* A program of the build (see dune): the soldier's pictures, PNG files
 * of data/, as the OCaml module the game carries them in,
 * Pictures_data.ml --
 *
 *   Gen_pictures.exe gostek-gfx/morda.png ... > Pictures_data.ml
 *
 * Each picture is decoded here and written as its pixels, 4 bytes
 * each (red, green, blue, alpha), in base64: the files carry up to 20
 * KB of other things for 2 KB of pixels, and the game then needs no
 * PNG decoder to show its soldier.
 *)

let read (file : string) : string =
  let chan = open_in_bin file in
  Fun.protect ~finally:(fun () -> close_in chan) (fun () -> really_input_string chan (in_channel_length chan))

let alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

let base64 (s : string) : string =
  let n = String.length s in
  let out = Buffer.create ((n + 2) / 3 * 4) in
  let byte i = if i < n then Char.code s.[i] else 0 in
  let rec go i =
    if i < n then begin
      let group = (byte i lsl 16) lor (byte (i + 1) lsl 8) lor byte (i + 2) in
      let char k = alphabet.[(group lsr (18 - (6 * k))) land 63] in
      Buffer.add_char out (char 0);
      Buffer.add_char out (char 1);
      Buffer.add_char out (if i + 1 < n then char 2 else '=');
      Buffer.add_char out (if i + 2 < n then char 3 else '=');
      go (i + 3)
    end
  in
  go 0;
  Buffer.contents out

let () =
  print_string "(* generated by src/render/Gen_pictures.ml from data/'s PNG files *)\n\n";
  print_string "(* each picture: its file's name without \".png\", its width, its height,\n * and its pixels (red, green, blue, alpha), rows from the top, in base64 *)\n";
  print_string "let all : (string * int * int * string) list =\n  [\n";
  List.iter
    (fun file ->
      let (image : Rgba_image.t) = Png.decode (read file) in
      let pixels = String.init (image.width * image.height * 4) (fun i -> Char.chr (Bigarray.Array1.get image.rgba i)) in
      Printf.printf "    (%S, %d, %d, %S);\n" (Filename.remove_extension (Filename.basename file)) image.width image.height (base64 pixels))
    (List.tl (Array.to_list Sys.argv));
  print_string "  ]\n"
