(* Claude Code
 *
 * Copyright (C) 2026 Yoann Padioleau
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public License
 * (LGPL) as published by the Free Software Foundation; either version
 * 2 of the License, or (at your option) any later version.
 *)
(* A program of the build (see dune): Soldat's animations, 1.2 MB of
 * text in data/anims/, as the OCaml module the game carries them in,
 * Anims_data.ml, 180 KB of numbers --
 *
 *   Gen_anims.exe gostek.po stoi.poa biega.poa ... > Anims_data.ml
 *
 * For each animation its file's name and how many frames it has, and
 * all the frames' points one after the other, each an x and a y as
 * the 4 bytes of a single (little-endian), what Soldat keeps them in:
 * nothing is lost that Soldat has. In base64, the smallest a string is
 * in a program compiled to JavaScript. The skeleton's file, small,
 * goes in as it is.
 *)

let read (file : string) : string =
  let chan = open_in_bin file in
  Fun.protect ~finally:(fun () -> close_in chan) (fun () -> really_input_string chan (in_channel_length chan))

let alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

let base64 (s : string) : string =
  let n = String.length s in
  let out = Buffer.create ((n + 2) / 3 * 4) in
  let byte i = if i < n then Char.code s.[i] else 0 in
  let rec go i =
    if i < n then begin
      let group = (byte i lsl 16) lor (byte (i + 1) lsl 8) lor byte (i + 2) in
      let char k = alphabet.[(group lsr (18 - (6 * k))) land 63] in
      Buffer.add_char out (char 0);
      Buffer.add_char out (char 1);
      Buffer.add_char out (if i + 1 < n then char 2 else '=');
      Buffer.add_char out (if i + 2 < n then char 3 else '=');
      go (i + 3)
    end
  in
  go 0;
  Buffer.contents out

let () =
  match List.tl (Array.to_list Sys.argv) with
  | [] -> failwith "usage: Gen_anims.exe gostek.po anim.poa..."
  | gostek :: files ->
      let bytes = Buffer.create 200_000 in
      let counts =
        List.map
          (fun file ->
            match Poa.animation (read file) with
            | Error why -> failwith (file ^ ": " ^ why)
            | Ok frames ->
                Array.iter (Array.iter (fun (x, y) -> Buffer.add_int32_le bytes (Int32.bits_of_float x); Buffer.add_int32_le bytes (Int32.bits_of_float y))) frames;
                (Filename.remove_extension (Filename.basename file), Array.length frames))
          files
      in
      print_string "(* generated by src/anim/Gen_anims.ml from data/anims/ and data/objects/ *)\n\n";
      print_string "(* each animation's file, and how many frames it has *)\nlet counts : (string * int) list =\n  [";
      List.iter (fun (name, n) -> Printf.printf " (%S, %d);" name n) counts;
      print_string " ]\n\n(* the frames' points, in that order: see Gen_anims.ml *)\nlet base64 : string =\n  {|";
      String.iteri (fun i c -> if i > 0 && i mod 76 = 0 then print_char '\n'; print_char c) (base64 (Buffer.contents bytes));
      print_string "|}\n\n(* objects/gostek.po, as it is *)\n";
      Printf.printf "let gostek : string = %S\n" (read gostek)
