#!/usr/bin/env python3
# Claude Code
#
# Copyright (C) 2026 Yoann Padioleau
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public License
# (LGPL) as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#
# Soldat's textures, each as its mean colour: src/map/Texture_tints.ml,
# what a map's polygons are filled with until they are filled with the
# texture itself. Run by hand when opensoldat-base's textures change
# (needs Pillow):
#
#   scripts/assets/texture_tints.py ~/work/GAMES/opensoldat-base > src/map/Texture_tints.ml
import os
import sys

from PIL import Image

base = sys.argv[1]
folder = os.path.join(base, "shared", "textures")
tints = {}
for name in sorted(os.listdir(folder)):
    stem, ext = os.path.splitext(name)
    if ext.lower() not in (".png", ".bmp"):
        continue
    pixels = list(Image.open(os.path.join(folder, name)).convert("RGB").getdata())
    mean = tuple(round(sum(p[i] for p in pixels) / len(pixels)) for i in range(3))
    # a map names its texture "banana.bmp" and the file is banana.png:
    # by its name without the extension, in small letters; a .png wins
    key = stem.lower()
    if key not in tints or ext.lower() == ".png":
        tints[key] = mean

print("(* generated by scripts/assets/texture_tints.py from opensoldat-base's")
print(" * shared/textures (CC BY 4.0): each texture's mean colour, by its file's")
print(" * name without the extension, in small letters *)")
print("let all : (string * (int * int * int)) list =")
print("  [")
for key, (r, g, b) in sorted(tints.items()):
    print('    ("%s", (%d, %d, %d));' % (key.replace("\\", "\\\\").replace('"', '\\"'), r, g, b))
print("  ]")
